name: $(Rev:r:)

variables:
    isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

jobs:
    - job: Test
      timeoutInMinutes: 20
      pool:
          vmImage: macOS-latest

      steps:
          - script: yarn --network-timeout 100000
            displayName: Install

          - script: yarn build
            displayName: Build

          # - script: yarn test
          #   displayName: Test

          # - script: |
          #       #!/bin/bash
          #       bash <(curl -s https://codecov.io/bash) -t $(CODECOV_TOKEN)
          #   condition: eq(variables.isMain, true)
          #   displayName: Publish Test Coverage

          # - script: yarn semantic-release
          #   env:
          #       GH_TOKEN: $(GH_TOKEN)
          #       NPM_TOKEN: $(NPM_TOKEN)
          #   condition: eq(variables.isMain, true)
          #   displayName: Semantic Release

          - task: ArchiveFiles@2
            # condition: eq(variables.isMain, true)
            inputs:
                rootFolderOrFile: lib
                includeRootFolder: true
                archiveType: zip
                archiveFile: code
                replaceExistingArchive: true

          - task: S3Upload@1
            # condition: eq(variables.isMain, true)
            inputs:
                awsCredentials: lambda-deploy
                regionName: ap-southeast-2
                bucketName: code-review-leaderboard
                globExpressions: code.zip
                createBucket: true

          - task: LambdaDeployFunction@1
            # condition: eq(variables.isMain, true)
            inputs:
                awsCredentials: lambda-deploy
                regionName: ap-southeast-2
                deploymentMode: codeonly
                functionName: code-review-leaderboard
                codeLocation: s3object
                s3Bucket: code-review-leaderboard
                s3ObjectKey: code.zip
